# Generated by Django 4.2.3 on 2023-07-04 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BeerTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('Belgian', 'Belgian'), ('Dark Beer', 'Dark Beer'), ('India Pale Ale', 'India Pale Ale'), ('Pale Ale/Red Ale', 'Pale Ale/Red Ale'), ('Pils/Lager/Weiss', 'Pils/Lager/Weiss')], max_length=150)),
                ('price', models.IntegerField()),
                ('quantity', models.CharField(max_length=150)),
                ('alcohol_level', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('in_stock', models.BooleanField(default=True)),
            ],
        ),
    ]
