# Generated by Django 4.2.3 on 2023-07-05 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beertypes',
            name='price',
            field=models.CharField(max_length=150),
        ),
    ]
